name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache env files
      uses: actions/cache@v3
      with:
        key: env-files
        path: ./env ./data   

    - name: Setup build env
      run: .\setup.bat

    - name: Build for Windows
      run: ./pack.sh win -p windows
      shell: bash

    - name: Build for Android
      run: ./pack.sh win -p android
      shell: bash

    - name: Build for iOS
      run: .\build.bat -p ios

    - name: Upload Windows pack
      uses: actions/upload-artifact@v3
      with:
        name: newb-x-windows
        path: ./build/windows/temp

    - name: Upload Android pack
      uses: actions/upload-artifact@v3
      with:
        name: newb-x-android
        path: ./build/android/temp

    - name: Upload iOS materials
      uses: actions/upload-artifact@v3
      with:
        name: newb-x-ios-materials
        path: ./build/ios

